<a href="https://colab.research.google.com/github/vaishnavi-gujare/NumPy-Assignment-Solutions/blob/main/13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1, 3, 6],
    [6, 7, 9],
    [4, 8, 6]
    ])
print("1D array", arr)
print("2D array", arr2)
print("1D Array shape", arr.shape)
print("2D Array shape", arr2.shape)
print("1D Array data type", arr.dtype)
print("2D Array data type", arr2.dtype)

1D array [10 20 30 40 50]
2D array [[1 3 6]
 [6 7 9]
 [4 8 6]]
1D Array shape (5,)
2D Array shape (3, 3)
1D Array data type int64
2D Array data type int64


In [4]:
arr1 = np.zeros(8)
arr2 = np.ones((4, 4))
arr3 = np.zeros((3, 3))
print("1D array of zeros:", arr1)
print("2D array of shape(4, 4):", arr2)
print("3 * 3 matrix of zeros:", arr3)

1D array of zeros: [0. 0. 0. 0. 0. 0. 0. 0.]
2D array of shape(4, 4): [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
3 * 3 matrix of zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
n1 = np.arange(0, 20, 2)
print("Numbers from 0 to 20:", n1)
n2 = np.arange(10, 50, 2)
print("Even numbers:", n2)
n3 = np.arange(5, 100, 5)
print("numbers from 5 to 100 with step 5", n3)

Numbers from 0 to 20: [ 0  2  4  6  8 10 12 14 16 18]
Even numbers: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
numbers from 5 to 100 with step 5 [ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [16]:
n1 = np.linspace(0, 5, 10)
print(" 10 equally spaced numbers :", n1, "length:", len(n1))
n2 = np.linspace(-10, 10, 15)
print("15 equally spaced numbers :", n2, "length:", len(n2))

 10 equally spaced numbers : [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ] length: 10
15 equally spaced numbers : [-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ] length: 15


In [22]:
rn = np.random.rand(10)
print("10 Random Numbers", rn)
rn2 = np.random.randn(3, 3)
print("3,3 matrix of random numbers", rn2)S
rn3 = np.random.randint(10, 51, (4, 5))
print("Random integers:", rn3)

10 Random Numbers [0.10105469 0.78983073 0.75765828 0.7264363  0.59949503 0.71951082
 0.2872055  0.5728145  0.41368168 0.91573161]
3,3 matrix of random numbers [[ 0.22759611  1.05377412 -0.48399945]
 [ 1.57087968  1.78146893  0.33782924]
 [-0.53276955  0.38548212  1.38410237]]
Random integers: [[23 14 47 17 49]
 [27 15 13 17 15]
 [42 22 15 25 43]
 [45 12 48 22 36]]


In [24]:
v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 3, 5, 7])
print(v1)
print(v2)
print("Addition:", v1 + v2)
print("Substraction:", v1 - v2)
print("Multiplication:", v1 * v2)
print("Dot product:", np.dot(v1, v2))

[2 4 6 8]
[1 3 5 7]
Addition: [ 3  7 11 15]
Substraction: [1 1 1 1]
Multiplication: [ 2 12 30 56]
Dot product: 100


In [27]:
A = np.array ([[1,2,3],
              [4,5,6],
              [7,8,9]])
B = np.array ([[9,8,7],
              [6,5,4],
              [3,2,1]])
print(A)
print(B)
print("Matrix Addition:", A + B)
print("Matrix Multiplication:", np.dot(A, B))
print("Element wise multiplication:", A * B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
Matrix Addition: [[10 10 10]
 [10 10 10]
 [10 10 10]]
Matrix Multiplication: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Element wise multiplication: [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [28]:
arr = np.random.randint(1, 101, (4, 4))
print("Matrix", arr)
print("Shape:", arr.shape)
print("Dimension (ndim):", arr.ndim)
print("Total number of element:", arr.size)
print("Data type:", arr.dtype)
print("Minimum value:", arr.min())
print("Maximum value:", arr.max())

Matrix [[17 69 88 14]
 [ 8 29 15 34]
 [94  2 34 96]
 [61 95 58 42]]
Shape: (4, 4)
Dimension (ndim): 2
Total number of element: 16
Data type: int64
Minimum value: 2
Maximum value: 96


In [29]:
arr = np.random.randint(1, 51, 20)
matrix = arr.reshape(4, 5)
print("4, 5 Matrix:", matrix)
print("Sum:", matrix.sum())
print("Mean:", matrix.mean())
print("Standard Division:", matrix.std())
print("Maximum value in each row:", matrix.max(axis=1))

4, 5 Matrix: [[12 41 12 43  1]
 [37 37 43 25 31]
 [ 9 35 31 34 35]
 [15 27  8 37 19]]
Sum: 532
Mean: 26.6
Standard Division: 12.7216351150314
Maximum value in each row: [43 43 35 37]


In [35]:
import numpy as np
try:
  n = int(input("How many numbers do you want to generate?"))
  if n <= 0:
    raise ValueError("Number must be greater than 0")
    arr = np.random.randint(10, 101, n)
    print("Generated Array:", arr)
    print("Statistics:")
    print("Mean:", np.mean(arr))
    print("Median:", np.median(arr))
    print("Standard Deviation:", np.std(arr))
    print("Minimum:", np.min(arr))
    print("Maximum:", np.max(arr))
    if n % 2 == 0:
      matrix = arr.reshape(2, n // 2)
      print("2D Array:", matrix)
      print("Row wise sum:", matrix.sum(axis=1))
    else:
      print("Cannot Reshape")
except ValueError as e:
  print("Error:", e)
except Exception as e:
    print("Unexpected Error:", e)

How many numbers do you want to generate?4


In [44]:
import numpy as np

try:
   n = int(input("How many numbers do you want to generate? "))
   if n <= 0:
      raise ValueError("Number must be greater than 0")
   arr = np.random.randint(10, 101, n)
   print("Generated Array:", arr)
   print("Statistics:")
   print("Mean:", np.mean(arr))
   print("Median:", np.median(arr))
   print("Standard Deviation:", np.std(arr))
   print("Minimum:", np.min(arr))
   print("Maximum:", np.max(arr))
   if n % 2 == 0:
      matrix = arr.reshape(2, n // 2)
      print("2D Array:", matrix)
      print("Row wise sum:", matrix.sum(axis=1))
   else:
       print("Cannot Reshape")
except ValueError as e:
  print("Error:", e)
except Exception as e:
    print("Unexpected Error:", e)

How many numbers do you want to generate? 4
Generated Array: [55 11 33 74]
Statistics:
Mean: 43.25
Median: 44.0
Standard Deviation: 23.60481942316018
Minimum: 11
Maximum: 74
2D Array: [[55 11]
 [33 74]]
Row wise sum: [ 66 107]
